"""empty message

Revision ID: 776f74c4556c
Revises: e7f4a39abb77
Create Date: 2025-04-21 20:31:36.780409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776f74c4556c'
down_revision = 'e7f4a39abb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
